FROM openjdk:11.0.2-jre-slim
COPY target/microservice-kubernetes-demo-order-0.0.1-SNAPSHOT.jar .
CMD /usr/bin/java -Xms512m -Xmx8g -jar microservice-kubernetes-demo-order-0.0.1-SNAPSHOT.jar
#EXPOSE 8082
EXPOSE 9097
