version: '3.7'

services:
#  apache:
#    image: clytze/microservice-kubernetes-demo-apache:latest
#    container_name: apache
#    ports:
#      - "80:80"
#    volumes:
#      - ./apache/index.html:/var/www/html/index.html
#      - ./apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
#    networks:
#      - microservice-network
#    depends_on:
#      - order
#      - catalog
#      - customer

  customer:
    image: clytze/microservice-kubernetes-demo-customer-rest:latest
    container_name: customer
    ports:
      - "9000:8080"
    networks:
      - microservice-network
    environment:
      - JAVA_OPTS=--illegal-access=permit

  catalog:
    image: clytze/microservice-kubernetes-demo-catalog-rest:latest
    container_name: catalog
    ports:
      - "9001:8080"
    networks:
      - microservice-network
    environment:
      - JAVA_OPTS=--illegal-access=permit

  order:
    image: clytze/microservice-kubernetes-demo-order-rest:latest
    container_name: order
    ports:
      - "9002:8080"
    networks:
      - microservice-network
    depends_on:
      - customer
      - catalog
    environment:
      - JAVA_OPTS=--illegal-access=permit

networks:
  microservice-network:
    driver: bridge
