version: '3.8'
services:
  customer-service-grpc:
    image: clytze/microservice-kubernetes-demo-customer-grpc
    ports:
      - "9096:9096" # gRPC
    networks:
      - microservice-network
    environment:
      - JAVA_OPTS=--illegal-access=permit


  catalog-service-grpc:
    image: clytze/microservice-kubernetes-demo-catalog-grpc
    ports:
      - "9095:9095" # gRPC
    networks:
      - microservice-network
    environment:
      - JAVA_OPTS=--illegal-access=permit

  order-service-grpc:
    image: clytze/microservice-kubernetes-demo-order-grpc
    ports:
      - "9097:9097" # gRPC
    networks:
      - microservice-network
    depends_on:
      - customer-service-grpc
      - catalog-service-grpc
    environment:
      - JAVA_OPTS=--illegal-access=permit

networks:
  microservice-network:
    driver: bridge
