# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import customer_pb2 as customer__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import order_pb2 as order__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in customer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class CustomerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getCustomer = channel.unary_unary(
                '/CustomerService/getCustomer',
                request_serializer=customer__pb2.CustomerRequest.SerializeToString,
                response_deserializer=customer__pb2.CustomerResponse.FromString,
                _registered_method=True)
        self.getCustomerList = channel.unary_unary(
                '/CustomerService/getCustomerList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=customer__pb2.CustomerListResponse.FromString,
                _registered_method=True)
        self.CreateCustomer = channel.unary_unary(
                '/CustomerService/CreateCustomer',
                request_serializer=customer__pb2.CreateCustomerRequest.SerializeToString,
                response_deserializer=customer__pb2.CustomerResponse.FromString,
                _registered_method=True)
        self.UpdateCustomer = channel.unary_unary(
                '/CustomerService/UpdateCustomer',
                request_serializer=customer__pb2.UpdateCustomerRequest.SerializeToString,
                response_deserializer=customer__pb2.CustomerResponse.FromString,
                _registered_method=True)
        self.DeleteCustomer = channel.unary_unary(
                '/CustomerService/DeleteCustomer',
                request_serializer=customer__pb2.CustomerRequest.SerializeToString,
                response_deserializer=order__pb2.SuccessResponse.FromString,
                _registered_method=True)


class CustomerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCustomerList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.getCustomer,
                    request_deserializer=customer__pb2.CustomerRequest.FromString,
                    response_serializer=customer__pb2.CustomerResponse.SerializeToString,
            ),
            'getCustomerList': grpc.unary_unary_rpc_method_handler(
                    servicer.getCustomerList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=customer__pb2.CustomerListResponse.SerializeToString,
            ),
            'CreateCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCustomer,
                    request_deserializer=customer__pb2.CreateCustomerRequest.FromString,
                    response_serializer=customer__pb2.CustomerResponse.SerializeToString,
            ),
            'UpdateCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCustomer,
                    request_deserializer=customer__pb2.UpdateCustomerRequest.FromString,
                    response_serializer=customer__pb2.CustomerResponse.SerializeToString,
            ),
            'DeleteCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCustomer,
                    request_deserializer=customer__pb2.CustomerRequest.FromString,
                    response_serializer=order__pb2.SuccessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CustomerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CustomerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CustomerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CustomerService/getCustomer',
            customer__pb2.CustomerRequest.SerializeToString,
            customer__pb2.CustomerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getCustomerList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CustomerService/getCustomerList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            customer__pb2.CustomerListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CustomerService/CreateCustomer',
            customer__pb2.CreateCustomerRequest.SerializeToString,
            customer__pb2.CustomerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CustomerService/UpdateCustomer',
            customer__pb2.UpdateCustomerRequest.SerializeToString,
            customer__pb2.CustomerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CustomerService/DeleteCustomer',
            customer__pb2.CustomerRequest.SerializeToString,
            order__pb2.SuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
