# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import order_pb2 as order__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ustomer.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0border.proto\"%\n\x0f\x43ustomerRequest\x12\x12\n\ncustomerId\x18\x01 \x01(\x03\"t\n\x10\x43ustomerResponse\x12\x12\n\ncustomerId\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tfirstname\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x0e\n\x06street\x18\x05 \x01(\t\x12\x0c\n\x04\x63ity\x18\x06 \x01(\t\"l\n\x08\x43ustomer\x12\x12\n\ncustomerId\x18\x01 \x01(\x03\x12\x11\n\tfirstname\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x0e\n\x06street\x18\x05 \x01(\t\x12\x0c\n\x04\x63ity\x18\x06 \x01(\t\"4\n\x14\x43ustomerListResponse\x12\x1c\n\tcustomers\x18\x01 \x03(\x0b\x32\t.Customer\"e\n\x15\x43reateCustomerRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tfirstname\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0e\n\x06street\x18\x04 \x01(\t\x12\x0c\n\x04\x63ity\x18\x05 \x01(\t\"y\n\x15UpdateCustomerRequest\x12\x12\n\ncustomerId\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tfirstname\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x0e\n\x06street\x18\x05 \x01(\t\x12\x0c\n\x04\x63ity\x18\x06 \x01(\t2\xb7\x02\n\x0f\x43ustomerService\x12\x32\n\x0bgetCustomer\x12\x10.CustomerRequest\x1a\x11.CustomerResponse\x12@\n\x0fgetCustomerList\x12\x16.google.protobuf.Empty\x1a\x15.CustomerListResponse\x12;\n\x0e\x43reateCustomer\x12\x16.CreateCustomerRequest\x1a\x11.CustomerResponse\x12;\n\x0eUpdateCustomer\x12\x16.UpdateCustomerRequest\x1a\x11.CustomerResponse\x12\x34\n\x0e\x44\x65leteCustomer\x12\x10.CustomerRequest\x1a\x10.SuccessResponseB8\n%com.ewolff.microservice.customer.grpcB\rCustomerProtoP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'customer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.ewolff.microservice.customer.grpcB\rCustomerProtoP\000'
  _globals['_CUSTOMERREQUEST']._serialized_start=60
  _globals['_CUSTOMERREQUEST']._serialized_end=97
  _globals['_CUSTOMERRESPONSE']._serialized_start=99
  _globals['_CUSTOMERRESPONSE']._serialized_end=215
  _globals['_CUSTOMER']._serialized_start=217
  _globals['_CUSTOMER']._serialized_end=325
  _globals['_CUSTOMERLISTRESPONSE']._serialized_start=327
  _globals['_CUSTOMERLISTRESPONSE']._serialized_end=379
  _globals['_CREATECUSTOMERREQUEST']._serialized_start=381
  _globals['_CREATECUSTOMERREQUEST']._serialized_end=482
  _globals['_UPDATECUSTOMERREQUEST']._serialized_start=484
  _globals['_UPDATECUSTOMERREQUEST']._serialized_end=605
  _globals['_CUSTOMERSERVICE']._serialized_start=608
  _globals['_CUSTOMERSERVICE']._serialized_end=919
# @@protoc_insertion_point(module_scope)
