# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x15\n\x07OrderId\x12\n\n\x02id\x18\x01 \x01(\x03\"+\n\x11OrderListResponse\x12\x16\n\x06orders\x18\x01 \x03(\x0b\x32\x06.Order\"&\n\rOrderResponse\x12\x15\n\x05order\x18\x01 \x01(\x0b\x32\x06.Order\"B\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\ncustomerId\x18\x02 \x01(\x03\x12\x19\n\x05lines\x18\x03 \x03(\x0b\x32\n.OrderLine\"8\n\tOrderLine\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x0e\n\x06itemId\x18\x02 \x01(\x03\x12\x0c\n\x04note\x18\x03 \x01(\t\"C\n\x12\x43reateOrderRequest\x12\x12\n\ncustomerId\x18\x01 \x01(\x03\x12\x19\n\x05lines\x18\x02 \x03(\x0b\x32\n.OrderLine\"7\n\x0e\x41\x64\x64LineRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x19\n\x05lines\x18\x02 \x03(\x0b\x32\n.OrderLine\")\n\x0fSuccessResponse\x12\x16\n\x0esuccessMessage\x18\x01 \x01(\t2\xf9\x01\n\x0cOrderService\x12\x38\n\nListOrders\x12\x16.google.protobuf.Empty\x1a\x12.OrderListResponse\x12$\n\x08GetOrder\x12\x08.OrderId\x1a\x0e.OrderResponse\x12\x32\n\x0b\x43reateOrder\x12\x13.CreateOrderRequest\x1a\x0e.OrderResponse\x12)\n\x0b\x44\x65leteOrder\x12\x08.OrderId\x1a\x10.SuccessResponse\x12*\n\x07\x41\x64\x64Line\x12\x0f.AddLineRequest\x1a\x0e.OrderResponseB2\n\"com.ewolff.microservice.order.grpcB\nOrderProtoP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"com.ewolff.microservice.order.grpcB\nOrderProtoP\000'
  _globals['_ORDERID']._serialized_start=44
  _globals['_ORDERID']._serialized_end=65
  _globals['_ORDERLISTRESPONSE']._serialized_start=67
  _globals['_ORDERLISTRESPONSE']._serialized_end=110
  _globals['_ORDERRESPONSE']._serialized_start=112
  _globals['_ORDERRESPONSE']._serialized_end=150
  _globals['_ORDER']._serialized_start=152
  _globals['_ORDER']._serialized_end=218
  _globals['_ORDERLINE']._serialized_start=220
  _globals['_ORDERLINE']._serialized_end=276
  _globals['_CREATEORDERREQUEST']._serialized_start=278
  _globals['_CREATEORDERREQUEST']._serialized_end=345
  _globals['_ADDLINEREQUEST']._serialized_start=347
  _globals['_ADDLINEREQUEST']._serialized_end=402
  _globals['_SUCCESSRESPONSE']._serialized_start=404
  _globals['_SUCCESSRESPONSE']._serialized_end=445
  _globals['_ORDERSERVICE']._serialized_start=448
  _globals['_ORDERSERVICE']._serialized_end=697
# @@protoc_insertion_point(module_scope)
